version: "2"

services:

    waf:
        image: dmgnx/nginx-naxsi
        restart: always
        ports:
            - "80:80"
        links:
            - frontend
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./ssl:/etc/nginx/ssl:ro
            - ./frontend/static:/usr/share/nginx/html/static:ro

    frontend:
        image: jlabusch/wrms-dash-frontend
        restart: always
        build: frontend
        expose:
            - "80"
        environment:
            - DJANGO_DEBUG
            - DJANGO_BACKEND_URI=http://api:80
            - DJANGO_SECRET
        links:
            - api
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./frontend/db.sqlite3:/opt/db.sqlite3

    api:
        image: jlabusch/wrms-dash-api
        restart: always
        build: api
        expose:
            - "80"
        entrypoint:
            - npm
            - start
        environment:
            - ICINGA_BASIC_AUTH
            - API_DEBUG
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./api/config/default.json:/opt/config/default.json:ro

